# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginRegistration', '0001_initial'),
        ('courses', '0002_comments_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='user',
            field=models.ManyToManyField(to='loginRegistration.User'),
        ),
    ]
