# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 21:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_courses_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='user',
            new_name='users',
        ),
    ]
