# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Email',
            new_name='Emails',
        ),
    ]
